_target_: src.model.ddpm.DDPM
image_shape:
  - 3
  - ${dataset.size}
  - ${dataset.size}
num_channels: 8
ch_mults: [1, 2, 2]
use_attn: [false, false, false]
num_blocks: 1
num_steps: 1000
beta_start: 0.0001
beta_end: 0.02
